version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile
      context: mutants-services
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network
  persistence:
    build:
      dockerfile: Dockerfile
      context: mutants-persistence
    ports:
      - 8081:8081
    networks:
      - spring-cloud-network
  amqp:
    build:
      dockerfile: Dockerfile
      context: mutants-amqp-messaging
    ports:
      - 8082:8082
    networks:
      - spring-cloud-network
    depends_on:
      - rabbitmq
networks:
    spring-cloud-network:
        driver: bridge